services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  shopper-backend:
    container_name: shopper-backend
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres-volume:
  node-volume:
